version: "3.9"

services:
  qr-html:
    image: nginx:alpine
    deploy:
      replicas: 1
    ports:
      - "8086:80"
    command: >
      sh -c "echo '<h1>QR funcionando correctamente</h1>' > /usr/share/nginx/html/index.html
      && nginx -g 'daemon off;'"
